### ISSUE TITLE
Is this available on Maven Central?

### ISSUE THREAD

**Issue by nanoandrew4** [nayuki/FLAC-library-Java#2]
Good day:

I'm interested in using your encoder/decoder in one of my own projects, but I can't seem to find this project on Maven Central. Is it available there, or is the source code all that's available?\

Thank you.

**Comment by nayuki** [comment]
This library is incomplete and not ready for publishing. The functionality is correct but is missing some useful features. The code lacks documentation comments and the project lacks an overview readme. Hence, this source code Git repository is all you get for now.
