### ISSUE TITLE
Using the FlacEncoder class to encode a PCM byte array to a FLAC file

### ISSUE THREAD

**Issue by nanoandrew4** [nayuki/FLAC-library-Java#3]
Good day:

I've been working on adding FLAC support to one of my programs, and I thought it'd be great to use your project, since it has an encoder and decoder. However, I cannot figure out how the encoder works. No matter how I try to arrange my sample data, it always throws an IllegalArgumentException once it reaches the computeBest() method. It probably has to do with how I'm converting the PCM data to the format that the FlacEncoder requires (an int[][]). 

Could you explain how that 2D int array should be constructed to work? I tried putting a sample in each array position, with index 0 being the left channel, and index 1 being the right channel, and that did not work. In essence, something like: samples[0][0] = leftChannelByte; samples[0][1] = rightChannelByte; etc...

I also tried flipping the use of indices in the array, so making the first dimension the number of channels, and the second the length of the PCM array divided by the number of channels (the opposite of what I outlined above), and that also failed.

In case it is relevant, I am using 2 channels, sample rate of 44100, block size of 4096 and SUBSET_BEST for search options.

Thank you.

**Comment by nayuki** [comment]
Hi, sorry for the late response.

> I also tried flipping the use of indices in the array, so making the first dimension the number of channels, and the second the length of the PCM array divided by the number of channels

This is the format that my library expects. You might be able to tell from reading my sample programs.

> However, I cannot figure out how the encoder works. No matter how I try to arrange my sample data, it always throws an IllegalArgumentException once it reaches the computeBest() method.

Try looking at which line is throwing the exception, and it should hopefully explain why you gave incorrect input data.
