### ISSUE TITLE
Flow diagram.

### ISSUE THREAD

**Issue by sanjaykrkundu** [nayuki/FLAC-library-Java#5]
is it possible to provide a flow diagram for the encoder and decoder.. ?

**Comment by nayuki** [comment]
Not right now. Please see the sample applications to learn how to use the library:
* [DecodeFlacToWav.java](https://github.com/nayuki/FLAC-library-Java/blob/c9b8727bab49f6da15f47c21bb67ef6de0306cad/src/io/nayuki/flac/app/DecodeFlacToWav.java)
* [EncodeWavToFlac.java](https://github.com/nayuki/FLAC-library-Java/blob/c9b8727bab49f6da15f47c21bb67ef6de0306cad/src/io/nayuki/flac/app/EncodeWavToFlac.java)
